<?php

/**
 * Copyright (C) 2025 Idayat Noufou  <contact@dev2a.pro>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

/**
 * Print admin page(s) tabs
 * 
 * @param  string $active Active tab title
 */
function print_debug_admin_tabs($active = 'Setup')
{
    $tabs = array(
        array('title' => 'Setup', 'url' => 'debug/admin/setup.php?mainmenu=home'),
        array('title' => 'Changelog', 'url' => 'debug/admin/changelog.php?mainmenu=home'),
        array('title' => 'About', 'url' => 'debug/admin/about.php?mainmenu=home')
    );

    foreach ($tabs as $key => $tab)
    {
        if ($tab['title'] == $active) {
            $tabs[$key]['active'] = true;
            break;
        }
    }

    print_tabs($tabs, 'Debug', 'debug.png@debug', -1);
}
