<?php

/**
 * Copyright (C) 2025 Idayat Noufou  <contact@dev2a.pro>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page, setup & debug lib
dol_include_once('debug/lib/page.lib.php');
dol_include_once('debug/lib/setup.lib.php');
dol_include_once('debug/lib/debug.lib.php');

// Control access to page
control_access('$user->admin');

// Get parameters
$action = GETPOST('action', 'alpha');

/**
 * Actions
 */

load_default_actions($action);

/**
 * View
 */

print_header('Setup', array('admin', 'debug@debug'));

print_subtitle('Setup', 'title_setup.png', 'link:modules_list');

print_debug_admin_tabs();

print_subtitle('Settings');


if (!in_array('mod_syslog_debug', array_keys($conf->loghandlers))) {
    $url = dol_buildpath('/admin/syslog.php', 2);
    print '<div class="warning">' . $langs->trans('DebugSyslogNotActivate', $url, $langs->trans('SyslogSetup')) . '</div>';
}

print_options(array(
    array('name' => 'DEBUG_PAGE_OK_POSITION', 'type' => 'select', 'desc' => 'DebugPageOkPosition', 'values' => array(
        'bottom-right' => 'BottomRight',
        'bottom-left' => 'BottomLeft',
        'top-right' => 'TopRight',
        'top-left' => 'TopLeft'
    )),
));
print_footer(true);
