<?php

/**
 * Copyright (C) 2025 Idayat Noufou  <contact@dev2a.pro>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page, setup & debug lib
dol_include_once('debug/lib/page.lib.php');
dol_include_once('debug/lib/setup.lib.php');
dol_include_once('debug/lib/debug.lib.php');

// Control access to page
control_access('$user->admin');

// Get parameters
$action = GETPOST('action', 'alpha');

/**
 * Actions
 */

load_default_actions($action);

/**
 * View
 */

print_header('Setup', array('admin', 'debug@debug'));

print_subtitle('Setup', 'title_setup.png', 'link:modules_list');

print_debug_admin_tabs('Setup');

print_trans('NoSetupAvailable');

// print_subtitle('Settings');

// print_options(array(
//     array('name' => 'MY_TEXT', 'type' => 'text', 'desc' => 'Text'),
//     array('name' => 'MY_NUMBER', 'type' => 'number', 'desc' => 'Number'),
//     array('name' => 'MY_SELECT', 'type' => 'select', 'desc' => 'Select', 'values' => array('Choice 1', 'Choice 2')),
//     array('name' => 'MY_MULTI_SELECT', 'type' => 'multiselect', 'desc' => 'Multi Select', 'values' => array('1' => 'Choice 1', '2' => 'Choice 2')),
//     array('name' => 'MY_COLOR', 'type' => 'color', 'desc' => 'Color'),
//     array('name' => 'MY_DATE', 'type' => 'date', 'desc' => 'Date'),
//     array('name' => 'MY_SWITCH', 'type' => 'switch', 'desc' => 'Switch'),
//     array('name' => 'MY_RANGE', 'type' => 'range', 'desc' => 'Range', 'min' => 0, 'max' => 10)
// ));

print_footer(true);
